import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'api_integration.dart';
import 'models.dart';

class DetailPage extends StatefulWidget {
  const DetailPage({super.key});
  @override
  State<DetailPage> createState() => _DetailPageState();
}

class _DetailPageState extends State<DetailPage> {
   List<GetApiModel>? userModelList = [];
getpost(){
  ApiService().getUsers().then((value){
    setState(() {
userModelList = value;
print(userModelList);
    });
  });
}


@override
  void initState() {

 getpost();
 print(userModelList);
    // TODO: implement initState
    super.initState();
  }

  Widget build(BuildContext context) {
    return  Scaffold(appBar: AppBar(title: Text('Get Api')),
      body: ListView.builder(
        itemBuilder: (context, index) {
          return Card(
            child: ListTile(title: Text("${userModelList?[index].title}"),
            subtitle: Text('${userModelList?[index].body}',),
              leading: Text("${userModelList?[index].id}"),
              titleTextStyle: TextStyle(fontWeight: FontWeight.w800,),
              titleAlignment: ListTileTitleAlignment.center,
            ),
          );
        },
        itemCount: userModelList?.length,
      ),
    );
  }
//get api__________
 // @override
  // Widget build(BuildContext context) {
  //   return  Scaffold(appBar: AppBar(title: Text('Get Api')),
  //     body: FutureBuilder(
  //       future: getUsers(),
  //       builder: (BuildContext context, AsyncSnapshot<List<Autogenerated>?> snapshot) {
  //         return   ListView.builder(
  //           itemBuilder: (context, index) {
  //             return Container(
  //               height: 200,
  //               margin: EdgeInsets.all(5),
  //               padding: EdgeInsets.all(10),
  //               //decoration: BoxDecoration(color: Colors.white54),
  //               color: Colors.lightBlueAccent,
  //               child:  Text(
  //                 "${userModelList![index].title}", textAlign: TextAlign.center,
  //               ),
  //             );
  //           },
  //           itemCount: userModelList?.length,
  //         );
  //       },
  //     ),
  //   );
  // }
  // get api response
  // Future<List<Autogenerated>?> getUsers() async {
  //   try {
  //   //  var url = Uri.parse("https://jsonplaceholder.typicode.com/posts");
  //     var response = await http.get(Uri.parse('https://jsonplaceholder.typicode.com/posts'));
  //     var data = jsonDecode(response.body.toString());
  //
  //
  //     if (response.statusCode == 200) {
  //       for(Map<String, dynamic> index   in data){
  //         userModelList?.add(Autogenerated.fromJson(index));
  //       }
  //       print(response.body);
  //       return userModelList;
  //       // return _model;
  //     }
  //     else{
  //       return userModelList;
  //     }
  //   }
  //   catch (e) {
  //    // log(e.toString());
  //   }
  // }
}

